blank_issues_enabled: false
contact_links:
  - name: Suggest a feature
    url: https://github.com/loopbackio/loopback-next/discussions/new?category=Ideas
    about: Share ideas for new features and discuss how to implementat them
  - name: Ask our community for help
    url: https://github.com/loopbackio/loopback-next/discussions/new?category=Q-A
    about: Post your question to our Discussions forum
  - name: Migration from LoopBack 3
    url: https://github.com/loopbackio/loopback-next/discussions/new?category=lb3-migration
    about: Get help with migrating your project from LoopBack 3 to LoopBack 4
  - name: Get help on StackOverflow
    url: https://stackoverflow.com/tags/loopbackjs
    about: You can also ask and answer questions on StackOverflow.
